# use in combination with the openshift.yaml file

global:
  drogueCloud:
    keycloak:
      insecure: true

drogueCloudCore:

  console:
    localCertificates: true

  integrations:
    websocket:
      ingress:
        insecure: true
        port: 80

  services:
    console:
      service:
        insecure: true
      ingress:
        insecure: true
        port: 80

    registry:
      service:
        insecure: true

    api:
      ingress:
        insecure: true
        port: 80

    sso:
      ingress:
        insecure: true
        port: 80

drogueCloudExamples:

  grafana:
    ingress:
      insecure: true
      port: 80
