drogueCloudCore:
  endpoints:
    coap:
      ingress:
        port: 443
    mqtt:
      ingress:
        port: 443
    mqttWs:
      ingress:
        port: 443
    mqttWsBrowser:
      ingress:
        port: 443
    http:
      ingress:
        port: 443

  integrations:
    mqtt:
      ingress:
        port: 443
    mqttWsBrowser:
      ingress:
        port: 443
    mqttWs:
      ingress:
        port: 443

global:
  drogueCloud:
    jaeger:
      enabled: false
      deployOperator: false # false for openshift
