global:
  drogueCloud:
    useServiceCA: true
    defaults:
      podSecurityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

drogueCloudCore:
  endpoints:
    coap:
      ingress:
        port: 443
    mqtt:
      ingress:
        port: 443
    mqttWs:
      ingress:
        port: 443
    mqttWsBrowser:
      ingress:
        port: 443
    http:
      ingress:
        port: 443

  integrations:
    mqtt:
      ingress:
        port: 443
    mqttWsBrowser:
      ingress:
        port: 443
    mqttWs:
      ingress:
        port: 443
